# Day 7 Practice: Ingest Live Dutch Weather into PostgreSQL

In this notebook you will perform your **first real ingestion**: call a live API, store the raw
response in Postgres, and prove your load is **idempotent**.

**Before you start:**
1. Read `14_theory_apis_and_ingestion.md`
2. Make sure the database is running:
   ```bash
   cd module-02-sql-elt-pipeline/project-nl-open-data-pipeline
   docker compose -f docker/docker-compose.yml up -d
   ```
3. Your module `.venv` is active and `requirements.txt` is installed (`requests` comes with it via jupyter; if missing: `pip install requests`)

## 1. Call the API

We fetch the last 7 days of daily weather for **De Bilt** (the reference station of the Dutch
weather institute KNMI). Note the three professional habits from the theory doc: `params=`,
`timeout=`, `raise_for_status()`.

In [5]:
from datetime import date, timedelta

import requests

CITY = "De Bilt"
LAT, LON = 52.10, 5.18

end = date.today() - timedelta(days=1)      # yesterday (today is still incomplete)
print("end:", end)
start = end - timedelta(days=6)             # 7-day overlapping window
print("start:", start)
print("today:", date.today())
print("timedelta:", timedelta(days=1))

response = requests.get(
    "https://archive-api.open-meteo.com/v1/archive",
    params={
        "latitude": LAT,
        "longitude": LON,
        "start_date": start.isoformat(),
        "end_date": end.isoformat(),
        "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum",
        "timezone": "Europe/Amsterdam",
    },
    timeout=30,
)
response.raise_for_status()
payload = response.json()

print("Status:", response.status_code)
print("Top-level keys:", list(payload.keys()))
payload["daily"]

end: 2026-08-17
start: 2026-08-11
today: 2026-08-18
timedelta: 1 day, 0:00:00
Status: 200
Top-level keys: ['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'daily_units', 'daily']

{'time': ['2026-08-11',
  '2026-08-12',
  '2026-08-13',
  '2026-08-14',
  '2026-08-15',
  '2026-08-16',
  '2026-08-17'],
 'temperature_2m_max': [22.7, 28.3, 31.6, 33.3, 23.7, 23.4, 19.7],
 'temperature_2m_min': [12.4, 12.5, 17.1, 18.3, 18.5, 15.8, 14.9],
 'precipitation_sum': [0.0, 0.0, 0.0, 0.0, 3.2, 0.3, 5.4]}

Expected: status `200`, and a `daily` dict of **parallel arrays** — `time`,
`temperature_2m_max`, `temperature_2m_min`, `precipitation_sum`, all the same length (7).

*(If the most recent day shows `None` values, that's the archive still catching up — a real-world
data quality fact! Our overlapping-window strategy exists exactly for this.)*

## 2. Reshape: parallel arrays → one record per day

The API is column-oriented; our raw table wants one row per `(city, date)`. `zip()` does the
pivot:

In [11]:
import json

daily = payload["daily"]

records = [
    {
        "city": CITY,
        "obs_date": d,
        "payload": json.dumps(
            {"temp_max": tmax, "temp_min": tmin, "precip_mm": prec}
        ),
    }
    for d, tmax, tmin, prec in zip(
        daily["time"],
        daily["temperature_2m_max"],
        daily["temperature_2m_min"],
        daily["precipitation_sum"],
    )
]

print(f"{len(records)} records")
records[0]

7 records

{'city': 'De Bilt',
 'obs_date': '2026-08-11',
 'payload': '{"temp_max": 22.7, "temp_min": 12.4, "precip_mm": 0.0}'}

## 3. Create the raw layer

Day 6 rules: a `raw` schema, a `JSONB` column for the payload as-received, and a **unique
constraint on the natural key** `(city, obs_date)` — the foundation of idempotency.

In [15]:
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://student:student123@localhost:5432/week2_db")

with engine.begin() as conn:   # engine.begin() = auto-commit the transaction at the end
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS raw"))
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS raw.weather_daily (
            city        TEXT        NOT NULL,
            obs_date    DATE        NOT NULL,
            payload     JSONB       NOT NULL,
            loaded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT weather_daily_pk PRIMARY KEY (city, obs_date)
        )
    """))

print("raw.weather_daily ready")

raw.weather_daily ready

In [17]:
# My version without SQLAlchemy, using psycopg2 directly. This is commented out because the SQLAlchemy version is preferred.
# import psycopg2

# cnn = psycopg2.connect(
#     host="localhost",
#     port=5432,
#     dbname="week2_db",
#     user="student",
#     password="student123",
# )
# try:
#     with cnn.cursor() as cur:
#         # creat schema and table if not exists
#         cur.execute("CREATE SCHEMA IF NOT EXISTS raw")
#         cur.execute("""
#             CREATE TABLE IF NOT EXISTS raw.weather_daily (
#                 city        TEXT        NOT NULL,
#                 obs_date    DATE        NOT NULL,
#                 payload     JSONB       NOT NULL,
#                 loaded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
#                 CONSTRAINT weather_daily_pk PRIMARY KEY (city, obs_date)
#             )
#         """)
# except Exception:
#     cnn.rollback()
#     raise
# finally:
#     cnn.close()

## 4. Load with an UPSERT (the light switch, not the staircase)

In [22]:
UPSERT_SQL = text("""
    INSERT INTO raw.weather_daily (city, obs_date, payload)
    VALUES (:city, :obs_date, CAST(:payload AS JSONB))
    ON CONFLICT (city, obs_date)
    DO UPDATE SET payload = EXCLUDED.payload,
                  loaded_at = now()
""")

with engine.begin() as conn:
    conn.execute(UPSERT_SQL, records)   # one call, executed per record

with engine.connect() as conn:
    n = conn.execute(text("SELECT count(*) FROM raw.weather_daily")).scalar()
print(f"Rows in raw.weather_daily: {n}")

Rows in raw.weather_daily: 7

## 5. Prove idempotency

**Re-run the cell above** (the upsert). Then check the count again below.

If the count is unchanged → your load is idempotent: reruns, retries and overlapping windows are
all safe. If the count doubled, you built a staircase — check your `ON CONFLICT` clause.

In [23]:
with engine.connect() as conn:
    n2 = conn.execute(text("SELECT count(*) FROM raw.weather_daily")).scalar()
print(f"Rows after re-running the upsert: {n2}   (expected: same as before)")

Rows after re-running the upsert: 7   (expected: same as before)

## 6. Query inside JSONB

The payload is stored as-received, but Postgres can reach inside it: `payload ->> 'temp_max'`
extracts a field **as text** (hence the cast).

In [21]:
import pandas as pd

df = pd.read_sql(
    """
    SELECT city,
           obs_date,
           (payload ->> 'temp_max')::numeric  AS temp_max_c,
           (payload ->> 'temp_min')::numeric  AS temp_min_c,
           (payload ->> 'precip_mm')::numeric AS precip_mm
    FROM raw.weather_daily
    ORDER BY obs_date
    """,
    engine,
)
df

      city    obs_date  temp_max_c  temp_min_c  precip_mm
0  De Bilt  2026-08-11        22.7        12.4        0.0
1  De Bilt  2026-08-12        28.3        12.5        0.0
2  De Bilt  2026-08-13        31.6        17.1        0.0
3  De Bilt  2026-08-14        33.3        18.3        0.0
4  De Bilt  2026-08-15        23.7        18.5        3.2
5  De Bilt  2026-08-16        23.4        15.8        0.3
6  De Bilt  2026-08-17        19.7        14.9        5.4

## ✏️ Try It Yourself 1 — Add more cities

Turn the fetch into a loop over multiple Dutch cities and load them all. Coordinates:

| City | Lat | Lon |
|------|-----|-----|
| Amsterdam | 52.37 | 4.90 |
| Rotterdam | 51.92 | 4.48 |
| Eindhoven | 51.44 | 5.48 |
| Groningen | 53.22 | 6.57 |
| Maastricht | 50.85 | 5.69 |

Requirements: a `CITIES` dict, one function `fetch_city(name, lat, lon) -> list[dict]`, a small
`time.sleep(0.5)` between API calls (polite citizen!), one upsert per city. Afterwards,
`SELECT city, count(*) FROM raw.weather_daily GROUP BY city` should show 7 rows per city.

In [ ]:
# Your code here
# Turn the fetch into a loop over multiple Dutch cities and load them all

CITIES = [
    ("De Bilt", 52.10, 5.18),
    ("Amsterdam", 52.37, 4.90),
    ("Rotterdam", 51.92, 4.48),
    ("Utrecht", 52.09, 5.12),
    ("Eindhoven", 51.44, 5.48),
]

def fetch_weather_data(city, lat, lon, start_date, end_date):
    response = requests.get(
        "https://archive-api.open-meteo.com/v1/archive",
        params={
            "latitude": lat,
            "longitude": lon,
            "start_date": start_date.isoformat(),
            "end_date": end_date.isoformat(),
            "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum",
            "timezone": "Europe/Amsterdam",
        },
        timeout=30,
    )
    response.raise_for_status()
    payload = response.json()
    daily = payload["daily"]
    records = [
        {
            "city": city,
            "obs_date": d,
            "payload": json.dumps(
                {"temp_max": tmax, "temp_min": tmin, "precip_mm": prec}
            ),
        }
        for d, tmax, tmin, prec in zip(
            daily["time"],
            daily["temperature_2m_max"],
            daily["temperature_2m_min"],
            daily["precipitation_sum"],
        )
    ]
    return records

for city, lat, lon in CITIES:
    records = fetch_weather_data(city, lat, lon, start, end)
    with engine.begin() as conn:
        conn.execute(UPSERT_SQL, records)
    print(f"Inserted/updated {len(records)} records for {city}")

Inserted/updated 7 records for De Bilt
Inserted/updated 7 records for Amsterdam
Inserted/updated 7 records for Rotterdam
Inserted/updated 7 records for Utrecht
Inserted/updated 7 records for Eindhoven

In [26]:
pd.read_sql(
    """
    SELECT city,
           obs_date,
           (payload ->> 'temp_max')::numeric  AS temp_max_c,
           (payload ->> 'temp_min')::numeric  AS temp_min_c,
           (payload ->> 'precip_mm')::numeric AS precip_mm
    FROM raw.weather_daily      
    ORDER BY city, obs_date
    """,
    engine,
)

          city    obs_date  temp_max_c  temp_min_c  precip_mm
0    Amsterdam  2026-08-11        21.6        12.1        0.0
1    Amsterdam  2026-08-12        27.4        12.6        0.0
2    Amsterdam  2026-08-13        32.2        17.0        0.0
3    Amsterdam  2026-08-14        34.7        19.4        0.0
4    Amsterdam  2026-08-15        23.2        18.4        6.4
5    Amsterdam  2026-08-16        23.0        15.9        0.3
6    Amsterdam  2026-08-17        19.7        14.7        5.6
7      De Bilt  2026-08-11        22.7        12.4        0.0
8      De Bilt  2026-08-12        28.3        12.5        0.0
9      De Bilt  2026-08-13        31.6        17.1        0.0
10     De Bilt  2026-08-14        33.3        18.3        0.0
11     De Bilt  2026-08-15        23.7        18.5        3.2
12     De Bilt  2026-08-16        23.4        15.8        0.3
13     De Bilt  2026-08-17        19.7        14.9        5.4
14   Eindhoven  2026-08-11        24.1        12.6        0.0
15   Eindhoven  2026-08-12        29.4        13.7        0.0
16   Eindhoven  2026-08-13        34.6        18.5        0.0
17   Eindhoven  2026-08-14        36.0        19.7        0.0
18   Eindhoven  2026-08-15        29.2        19.4        1.2
19   Eindhoven  2026-08-16        24.6        16.1        0.0
20   Eindhoven  2026-08-17        20.8        14.7        6.0
21   Groningen  2026-08-11        19.3        12.5        0.0
22   Groningen  2026-08-12        24.2        10.1        0.0
23   Groningen  2026-08-13        29.5        14.7        0.0
24   Groningen  2026-08-14        33.0        17.4        0.0
25   Groningen  2026-08-15        22.1        16.1        4.6
26   Groningen  2026-08-16        22.1        12.2        0.2
27   Groningen  2026-08-17        19.4        13.9        2.9
28  Maastricht  2026-08-11        25.7        13.9        0.0
29  Maastricht  2026-08-12        30.5        15.5        0.0
30  Maastricht  2026-08-13        35.2        18.1        0.0
31  Maastricht  2026-08-14        35.7        21.1        0.0
32  Maastricht  2026-08-15        29.9        20.9        0.1
33  Maastricht  2026-08-16        26.5        16.9        0.0
34  Maastricht  2026-08-17        21.9        15.1        4.2
35   Rotterdam  2026-08-11        23.5        13.7        0.0
36   Rotterdam  2026-08-12        27.9        14.1        0.0
37   Rotterdam  2026-08-13        32.3        18.1        0.0
38   Rotterdam  2026-08-14        35.0        20.4        0.0
39   Rotterdam  2026-08-15        26.4        19.4        1.8
40   Rotterdam  2026-08-16        24.6        17.5        0.0
41   Rotterdam  2026-08-17        20.3        16.1        4.8
42     Utrecht  2026-08-11        23.3        12.6        0.0
43     Utrecht  2026-08-12        28.3        12.8        0.0
44     Utrecht  2026-08-13        31.9        17.5        0.0
45     Utrecht  2026-08-14        34.0        19.0        0.0
46     Utrecht  2026-08-15        24.5        18.7        2.1
47     Utrecht  2026-08-16        23.6        16.2        0.1
48     Utrecht  2026-08-17        19.9        15.1        5.1

<details>
<summary>💡 Click to reveal solution</summary>

```python
import time

CITIES = {
    "De Bilt": (52.10, 5.18),
    "Amsterdam": (52.37, 4.90),
    "Rotterdam": (51.92, 4.48),
    "Eindhoven": (51.44, 5.48),
    "Groningen": (53.22, 6.57),
    "Maastricht": (50.85, 5.69),
}

def fetch_city(name: str, lat: float, lon: float) -> list[dict]:
    r = requests.get(
        "https://archive-api.open-meteo.com/v1/archive",
        params={
            "latitude": lat,
            "longitude": lon,
            "start_date": start.isoformat(),
            "end_date": end.isoformat(),
            "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum",
            "timezone": "Europe/Amsterdam",
        },
        timeout=30,
    )
    r.raise_for_status()
    d = r.json()["daily"]
    return [
        {
            "city": name,
            "obs_date": day,
            "payload": json.dumps({"temp_max": tmax, "temp_min": tmin, "precip_mm": prec}),
        }
        for day, tmax, tmin, prec in zip(
            d["time"], d["temperature_2m_max"], d["temperature_2m_min"], d["precipitation_sum"]
        )
    ]

for name, (lat, lon) in CITIES.items():
    rows = fetch_city(name, lat, lon)
    with engine.begin() as conn:
        conn.execute(UPSERT_SQL, rows)
    print(f"{name}: {len(rows)} rows upserted")
    time.sleep(0.5)

pd.read_sql("SELECT city, count(*) FROM raw.weather_daily GROUP BY city ORDER BY city", engine)
```

</details>

## ✏️ Try It Yourself 2 — Build the staging layer

Day 6 said: *raw gets upserts, derived tables get rebuilt.* Do it: create a `staging` schema and
rebuild a `staging.weather_clean` table from `raw.weather_daily` with:

- typed columns: `city TEXT`, `obs_date DATE`, `temp_max_c NUMERIC`, `temp_min_c NUMERIC`, `precip_mm NUMERIC`
- rows where `temp_max` is missing in the payload **filtered out** (data quality gate)

Then run your whole notebook top to bottom a second time and confirm nothing breaks and no counts
double — a full idempotency test.

In [28]:
# Your code here
# lets make create a `staging` schema and rebuild a `staging.weather_clean` table from `raw.weather_daily` with:
# typed columns: `city TEXT`, `obs_date DATE`, `temp_max_c NUMERIC`, `temp_min_c NUMERIC`, `precip_mm NUMERIC`
# rows where `temp_max` is missing in the payload **filtered out** (data quality gate)

with engine.begin() as conn:
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS staging"))
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS staging.weather_clean (
            city        TEXT        NOT NULL,
            obs_date    DATE        NOT NULL,
            temp_max_c  NUMERIC     NOT NULL,
            temp_min_c  NUMERIC     NOT NULL,
            precip_mm   NUMERIC     NOT NULL,
            loaded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT weather_clean_pk PRIMARY KEY (city, obs_date)
        )
    """))

    conn.execute(text("""
        INSERT INTO staging.weather_clean (city, obs_date, temp_max_c, temp_min_c, precip_mm)
        SELECT city,
               obs_date,
               (payload ->> 'temp_max')::numeric AS temp_max_c,
               (payload ->> 'temp_min')::numeric AS temp_min_c,
               (payload ->> 'precip_mm')::numeric AS precip_mm
        FROM raw.weather_daily
        WHERE payload ->> 'temp_max' IS NOT NULL
        ON CONFLICT (city, obs_date) DO UPDATE SET
            temp_max_c = EXCLUDED.temp_max_c,
            temp_min_c = EXCLUDED.temp_min_c,
            precip_mm = EXCLUDED.precip_mm,
            loaded_at = now()
    """))


pd.read_sql(
    """
    SELECT city,
           obs_date,
           temp_max_c,
           temp_min_c,
           precip_mm
    FROM staging.weather_clean              
    ORDER BY city, obs_date
    """,
    engine,
)

          city    obs_date  temp_max_c  temp_min_c  precip_mm
0    Amsterdam  2026-08-11        21.6        12.1        0.0
1    Amsterdam  2026-08-12        27.4        12.6        0.0
2    Amsterdam  2026-08-13        32.2        17.0        0.0
3    Amsterdam  2026-08-14        34.7        19.4        0.0
4    Amsterdam  2026-08-15        23.2        18.4        6.4
5    Amsterdam  2026-08-16        23.0        15.9        0.3
6    Amsterdam  2026-08-17        19.7        14.7        5.6
7      De Bilt  2026-08-11        22.7        12.4        0.0
8      De Bilt  2026-08-12        28.3        12.5        0.0
9      De Bilt  2026-08-13        31.6        17.1        0.0
10     De Bilt  2026-08-14        33.3        18.3        0.0
11     De Bilt  2026-08-15        23.7        18.5        3.2
12     De Bilt  2026-08-16        23.4        15.8        0.3
13     De Bilt  2026-08-17        19.7        14.9        5.4
14   Eindhoven  2026-08-11        24.1        12.6        0.0
15   Eindhoven  2026-08-12        29.4        13.7        0.0
16   Eindhoven  2026-08-13        34.6        18.5        0.0
17   Eindhoven  2026-08-14        36.0        19.7        0.0
18   Eindhoven  2026-08-15        29.2        19.4        1.2
19   Eindhoven  2026-08-16        24.6        16.1        0.0
20   Eindhoven  2026-08-17        20.8        14.7        6.0
21   Groningen  2026-08-11        19.3        12.5        0.0
22   Groningen  2026-08-12        24.2        10.1        0.0
23   Groningen  2026-08-13        29.5        14.7        0.0
24   Groningen  2026-08-14        33.0        17.4        0.0
25   Groningen  2026-08-15        22.1        16.1        4.6
26   Groningen  2026-08-16        22.1        12.2        0.2
27   Groningen  2026-08-17        19.4        13.9        2.9
28  Maastricht  2026-08-11        25.7        13.9        0.0
29  Maastricht  2026-08-12        30.5        15.5        0.0
30  Maastricht  2026-08-13        35.2        18.1        0.0
31  Maastricht  2026-08-14        35.7        21.1        0.0
32  Maastricht  2026-08-15        29.9        20.9        0.1
33  Maastricht  2026-08-16        26.5        16.9        0.0
34  Maastricht  2026-08-17        21.9        15.1        4.2
35   Rotterdam  2026-08-11        23.5        13.7        0.0
36   Rotterdam  2026-08-12        27.9        14.1        0.0
37   Rotterdam  2026-08-13        32.3        18.1        0.0
38   Rotterdam  2026-08-14        35.0        20.4        0.0
39   Rotterdam  2026-08-15        26.4        19.4        1.8
40   Rotterdam  2026-08-16        24.6        17.5        0.0
41   Rotterdam  2026-08-17        20.3        16.1        4.8
42     Utrecht  2026-08-11        23.3        12.6        0.0
43     Utrecht  2026-08-12        28.3        12.8        0.0
44     Utrecht  2026-08-13        31.9        17.5        0.0
45     Utrecht  2026-08-14        34.0        19.0        0.0
46     Utrecht  2026-08-15        24.5        18.7        2.1
47     Utrecht  2026-08-16        23.6        16.2        0.1
48     Utrecht  2026-08-17        19.9        15.1        5.1

<details>
<summary>💡 Click to reveal solution</summary>

```python
with engine.begin() as conn:
    conn.execute(text("CREATE SCHEMA IF NOT EXISTS staging"))
    conn.execute(text("DROP TABLE IF EXISTS staging.weather_clean"))
    conn.execute(text("""
        CREATE TABLE staging.weather_clean AS
        SELECT city,
               obs_date,
               (payload ->> 'temp_max')::numeric  AS temp_max_c,
               (payload ->> 'temp_min')::numeric  AS temp_min_c,
               (payload ->> 'precip_mm')::numeric AS precip_mm
        FROM raw.weather_daily
        WHERE payload ->> 'temp_max' IS NOT NULL
    """))

pd.read_sql("SELECT * FROM staging.weather_clean ORDER BY city, obs_date LIMIT 10", engine)
```

DROP + CREATE ... AS SELECT = the rebuild pattern: always the same result, however often you run it.

</details>

## 🎉 Wrap-up

You just did real data engineering: live API → raw JSONB layer with idempotent upserts → typed
staging layer. This notebook is the prototype of your project's `fetch.py` and `load.py`.

**Next (Day 8):** how professionals make sure this keeps working — `pytest` and your first
GitHub Actions workflow (including the cron schedule that will run this pipeline nightly).